### ISSUE TITLE
LineFragment.checkChildren Assertion failed

### ISSUE THREAD

**Issue by dkandalov** [dkandalov/limited-wip#2]
Happens even with change size watch and revert disabled.
IU-139.658.4 seems to occur with any .xml changes in default change list:
```java
Assertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:153)
	at com.intellij.openapi.diff.impl.fragments.LineFragment.checkChildren(LineFragment.java:199)
	at com.intellij.openapi.diff.impl.fragments.LineFragment.setChildren(LineFragment.java:182)
	at com.intellij.openapi.diff.impl.processing.TextCompareProcessor.process(TextCompareProcessor.java:80)
	at limitedwip.components.VcsIdeUtil.amountOfChangedLinesIn(VcsIdeUtil.java:63)
	at limitedwip.components.VcsIdeUtil.currentChangeListSizeInLines(VcsIdeUtil.java:40)
	at limitedwip.IdeActions$1.compute(IdeActions.java:47)
	at limitedwip.IdeActions$1.compute(IdeActions.java:44)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:928)
	at limitedwip.IdeActions.currentChangeListSizeInLines(IdeActions.java:44)
	at limitedwip.components.LimitedWIPProjectComponent$1.onTimerUpdate(LimitedWIPProjectComponent.java:66)
	at limitedwip.components.TimerEventsSource$1.run(TimerEventsSource.java:40)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by dkandalov** [comment]
Using these diff parameters fixes the problem:
new TextCompareProcessor(ComparisonPolicy.TRIM_SPACE, DiffPolicy.LINES_WO_FORMATTING, HighlightMode.BY_LINE)
