### ISSUE TITLE
not committing on test run

### ISSUE THREAD

**Issue by TrentonAdams** [dkandalov/limited-wip#32]
I'm on 2019.3 and it's not committing when I run tests.  Could the fix for #30 have caused this?

![image](https://user-images.githubusercontent.com/534192/71688314-df9beb00-2d5c-11ea-8e31-bbf4f0e84247.png)

**Comment by TrentonAdams** [comment]
FYI, I decided to see if there was some sort of funky caching issue caused by either my IDE upgrade or the plugin upgrade.  I unchecked the "Enable" box in the screen shot, click "Apply" then checked it and clicked "Apply" again.  The problem is now gone.  I ran tests several times before doing that and it refused to commit, then I ran tests after that and it committed.

I'll leave it open so the devs can determine if they want to look into fixing it, or have theories on what could cause that.

**Comment by dkandalov** [comment]
Thanks a lot for reporting the problem!
Unfortunately, there are no "devs" it's just myself looking into the issues and I didn't manage to reproduce this one so far 🙁 But please give a shout if you see it happening again.

Just to be sure, I assume you're using plugin version 0.3.9.

Issue #30 might be related but it was about plugin version 0.3.8 not working in EAP because of IJ API changes. It might also be related #28 but if you didn't get an error in IDE, then maybe not.

**Comment by TrentonAdams** [comment]
> Just to be sure, I assume you're using plugin version 0.3.9.
I would think so, as I was already past the version of IDEA that 0.3.8 was working on.  Plus, I have a normal practice of verifying what version I'm running, that it's up to date, etc, before I file any bugs for projects.  And since I mentioned "#30", I can't imagine having not checked that, that would be very outside my normal practice.  In either case, I can't completely confirm now as I've moved on to using a Mac, so everything is new now. :D

**Comment by TrentonAdams** [comment]
@dkandalov Have you considered asking IntelliJ folks to take over?  I feel like this is a really crucial plugin, it should come with IDEA by default. :D

**Comment by goerge** [comment]
For documentation purposes:

I had the same issue with IntelliJ 2021.2.3 Ultimate and Limited WIP 0.3.10 on macOS 12.0.1 with the following error in the log:
```
java.lang.NoSuchMethodError: 'void com.intellij.vcs.commit.SingleChangeListCommitter.<init>(com.intellij.openapi.project.Project, com.intellij.vcs.commit.ChangeListCommitState, com.intellij.openapi.vcs.changes.CommitContext, com.intellij.openapi.vcs.AbstractVcs, java.lang.String, boolean)'
	at limitedwip.common.vcs.CommitHelper.<init>(commit-without-dialog.kt:149)
	at limitedwip.common.vcs.Commit_without_dialogKt$doCommitWithoutDialog$runnable$1.run(commit-without-dialog.kt:65)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$CallbackBase.invokeCallback(InvokeAfterUpdateCallback.java:66)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$ProgressCallback$ModalWaiter.onFinished(InvokeAfterUpdateCallback.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:619)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:577)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:438)
	at com.intellij.openapi.application.ex.ApplicationUtil.invokeAndWaitSomewhere(ApplicationUtil.java:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:575)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:88)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:398)
	at com.intellij.openapi.progress.Task.queue(Task.java:124)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$ProgressCallback.startProgress(InvokeAfterUpdateCallback.java:127)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue.invokeAfterUpdate(UpdateRequestsQueue.java:169)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:380)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:368)
	at limitedwip.common.vcs.Commit_without_dialogKt.doCommitWithoutDialog(commit-without-dialog.kt:79)
	at limitedwip.tcr.components.Ide$amendCommitWithoutDialog$1.invoke(Ide.kt:34)
	at limitedwip.tcr.components.Ide$amendCommitWithoutDialog$1.invoke(Ide.kt:14)
	at limitedwip.common.vcs.Commit_and_pushKt$sam$Runnable$a14d6231.run(commit-and-push.kt)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

For whatever reason IntelliJ didn't see the "new" version (0.3.13) of the Limited WIP plugin so I had to uninstall and install the plugin. Et voilà, committing on green works fine.
So I assume, this issue can be closed.

Thanks for the great work. We had a lot of fun with TCR at the GDCR2021 in Vienna!
